"use client";
import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from "react";
export type Locale = "en" | "ms";
const translations = {
  en: { menuSearch:"Search dishes or drinks...", noMenu:"No menu items found.", all:"All", cart:"Cart", yourOrder:"Your order", remove:"Remove", each:"each", continueCheckout:"Continue to checkout", lastStep:"Last step", checkout:"Checkout", tableDetected:"Table detected from QR", notDetected:"Not detected", specialNote:"Special note", optional:"optional", notePlaceholder:"Example: less spicy...", paymentMethod:"Payment method", cash:"Cash", card:"Card", submitOrder:"Place order", submitting:"Submitting...", qrIncomplete:"Table QR is incomplete. Please open this page from a table QR code.", orderFailed:"Unable to send order. Your cart is still saved.", connectionFailed:"Connection failed. Your cart is still saved.", chooseContinue:"Choose how to continue your order", googleLogin:"Continue with Google", guestContinue:"Continue as guest", orderConfirmed:"Order confirmed", orderReceived:"Your order has been received and sent to the kitchen.", orderNumber:"Order number", status:"Status", payment:"Payment", trackOrder:"Track order", backToMenu:"Back to menu", foodDetail:"Food detail", addToCart:"Add to cart", signature:"Signature", language:"Language", english:"English", bahasaMelayu:"Bahasa Melayu", previewMenu:"Preview menu", pricesSst:"Prices subject to 6% SST", signIn:"Sign in", signInFailed:"Sign-in failed", signInFailedBody:"Something went wrong while signing you in with Google. Please try again, or continue as a guest.", email:"Email", password:"Password", invalidCredentials:"Invalid email or password. Please try again.", welcome:"Welcome.", signInDescription:"Sign in to continue your order.", loginGoogle:"Continue with Google", loginGuest:"Continue as guest", add:"Add", close:"Close", subtotal:"Subtotal", total:"Total", itemsInCart:"items in cart" },
  ms: { menuSearch:"Cari hidangan atau minuman...", noMenu:"Tiada menu ditemui.", all:"Semua", cart:"Cart", yourOrder:"Pesanan anda", remove:"Buang", each:"setiap satu", continueCheckout:"Teruskan ke checkout", lastStep:"Langkah terakhir", checkout:"Checkout", tableDetected:"Meja dikesan daripada QR", notDetected:"Belum dikesan", specialNote:"Nota khas", optional:"pilihan", notePlaceholder:"Contoh: kurang pedas...", paymentMethod:"Kaedah bayaran", cash:"Tunai", card:"Kad", submitOrder:"Sahkan pesanan", submitting:"Sedang menghantar...", qrIncomplete:"QR meja tidak lengkap. Sila buka halaman melalui QR code meja.", orderFailed:"Pesanan tidak dapat dihantar. Cart anda masih disimpan.", connectionFailed:"Sambungan gagal. Cart anda masih disimpan.", chooseContinue:"Pilih cara untuk teruskan pesanan", googleLogin:"Log masuk Google", guestContinue:"Teruskan sebagai guest", orderConfirmed:"Pesanan disahkan", orderReceived:"Pesanan anda telah diterima dan dihantar ke dapur.", orderNumber:"Nombor pesanan", status:"Status", payment:"Bayaran", trackOrder:"Jejak pesanan", backToMenu:"Kembali ke menu", foodDetail:"Butiran makanan", addToCart:"Tambah ke cart", signature:"Signature", language:"Bahasa", english:"English", bahasaMelayu:"Bahasa Melayu", previewMenu:"Preview menu", pricesSst:"Harga tertakluk kepada SST 6%", signIn:"Log masuk", signInFailed:"Log masuk gagal", signInFailedBody:"Sesuatu masalah berlaku semasa log masuk Google. Sila cuba lagi atau teruskan sebagai guest.", email:"Email", password:"Password", invalidCredentials:"Email atau password tidak sah. Sila cuba lagi.", welcome:"Selamat datang.", signInDescription:"Log masuk untuk meneruskan pesanan.", loginGoogle:"Teruskan dengan Google", loginGuest:"Teruskan sebagai guest", add:"Tambah", close:"Tutup", subtotal:"Subtotal", total:"Jumlah", itemsInCart:"item dalam cart" },
} as const;
type TranslationKey = keyof typeof translations.en;
type LanguageContextValue = { locale: Locale; setLocale: (locale: Locale) => void; t: (key: TranslationKey) => string };
const LanguageContext = createContext<LanguageContextValue | null>(null);
const STORAGE_KEY = "nangnyamai-locale";
export function LanguageProvider({ children }: { children: ReactNode }) { const [locale, setLocaleState] = useState<Locale>("en"); useEffect(() => { const saved = window.localStorage.getItem(STORAGE_KEY); if (saved === "en" || saved === "ms") window.setTimeout(() => setLocaleState(saved), 0); }, []); useEffect(() => { document.documentElement.lang = locale; }, [locale]); const setLocale = (next: Locale) => { setLocaleState(next); window.localStorage.setItem(STORAGE_KEY, next); }; const value = useMemo(() => ({ locale, setLocale, t: (key: TranslationKey) => translations[locale][key] }), [locale]); return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>; }
export function useLanguage() { const context = useContext(LanguageContext); if (!context) throw new Error("useLanguage must be used within LanguageProvider"); return context; }
