"use client";

import { useState, type FormEvent } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { LanguageSelector } from "@/components/shared/language-selector";
import { ThemeToggle } from "@/components/shared/theme-toggle";

type ProfileOrder = { id: string; order_number: string; total: number; status: string; payment_status: string; created_at: string };
export function ProfileForm({ fullName, phone, email, orders }: { fullName: string; phone: string; email: string; orders: ProfileOrder[] }) {
  const [name, setName] = useState(fullName); const [phoneValue, setPhoneValue] = useState(phone); const [message, setMessage] = useState<string | null>(null); const [saving, setSaving] = useState(false);
  async function save(event: FormEvent) { event.preventDefault(); setSaving(true); setMessage(null); const response = await fetch("/api/profile", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ fullName: name, phone: phoneValue }) }); setMessage(response.ok ? "Profile saved." : "Unable to save profile."); setSaving(false); }
  return <><div className="flex justify-end gap-2"><LanguageSelector /><ThemeToggle /></div><section className="rounded-[var(--radius-xl)] border border-[var(--soft-sand)] bg-[var(--surface)] p-6 shadow-sm"><h2 className="text-xl font-bold text-[var(--text-primary)]">Your details</h2><form className="mt-5 space-y-4" onSubmit={save}><label className="block text-sm font-semibold text-[var(--text-primary)]">Email<Input value={email} readOnly className="mt-2" /></label><label className="block text-sm font-semibold text-[var(--text-primary)]">Full name<Input value={name} onChange={(event) => setName(event.target.value)} maxLength={120} className="mt-2" /></label><label className="block text-sm font-semibold text-[var(--text-primary)]">Phone number<Input value={phoneValue} onChange={(event) => setPhoneValue(event.target.value)} maxLength={30} placeholder="+60 12 345 6789" className="mt-2" /></label>{message && <p role="status" className="text-sm text-[var(--text-secondary)]">{message}</p>}<Button type="submit" disabled={saving}>{saving ? "Saving..." : "Save changes"}</Button></form></section><section className="rounded-[var(--radius-xl)] border border-[var(--soft-sand)] bg-[var(--surface)] p-6 shadow-sm"><h2 className="text-xl font-bold text-[var(--text-primary)]">Order history</h2>{orders.length === 0 ? <p className="mt-2 text-sm text-[var(--text-secondary)]">No orders yet.</p> : <div className="mt-4 space-y-3">{orders.map((order) => <a key={order.id} href={`/order/${order.id}`} className="block rounded-[var(--radius-md)] border border-[var(--soft-sand)] p-4"><div className="flex justify-between gap-3 font-semibold text-[var(--text-primary)]"><span>#{order.order_number}</span><span>RM {Number(order.total).toFixed(2)}</span></div><p className="mt-1 text-sm text-[var(--text-secondary)]">{order.status} · {order.payment_status}</p></a>)}</div>}</section></>;
}
