"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";

type Receipt = { order_number: string; customer_id: string | null; subtotal: number; service_charge: number; total: number; status: string; payment_status: string; payment_method: string | null; created_at: string; updated_at: string; restaurant_tables: { table_number: string } | null; order_items: { item_name_snapshot: string; unit_price: number; quantity: number }[] };
type CustomerProfile = { full_name: string | null; phone: string | null; member_id: string | null };
const money = (value: number) => Number(value).toFixed(2);

export function DigitalReceipt({ orderId }: { orderId: string }) {
  const supabase = useMemo(() => createClient(), []); const [order, setOrder] = useState<Receipt | null>(null); const [customer, setCustomer] = useState<CustomerProfile | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); setCustomer(null); const { data, error: queryError } = await supabase.from("orders").select("order_number, customer_id, subtotal, service_charge, total, status, payment_status, payment_method, created_at, updated_at, restaurant_tables!orders_table_id_fkey(table_number), order_items(item_name_snapshot, unit_price, quantity)").eq("id", orderId).eq("status", "completed").eq("payment_status", "paid").maybeSingle(); if (queryError) setError("Unable to load the receipt right now."); else if (!data) setError("Receipt is not available for this order."); else { const receipt = data as unknown as Receipt; setOrder(receipt); if (receipt.customer_id) { const { data: profile } = await supabase.rpc("get_receipt_customer_profile", { p_order_id: orderId }); setCustomer((profile as CustomerProfile[] | null)?.[0] ?? null); } } setLoading(false); }, [orderId, supabase]);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  if (loading) return <main className="receipt-page"><span>Loading receipt…</span></main>;
  const valid = order && order.status === "completed" && order.payment_status === "paid" && (order.payment_method === "cash" || order.payment_method === "card");
  if (!order || !valid) return <main className="receipt-page"><Link className="details-back receipt-control" href="/staff/payments">← <span>Back to Payment Processing</span></Link><div className="status-error">{error || "Receipt is not available for this order."}</div></main>;
  const customerName = customer?.full_name || "—"; const phone = customer?.phone || "—"; const memberId = customer?.member_id || "—";
  return <main className="receipt-page"><div className="receipt-controls"><Link className="details-back" href={`/staff/payments/${orderId}/complete`}>← <span>Back to Payment Successful</span></Link><button type="button" onClick={() => window.print()}>Print Receipt</button></div><article className="digital-receipt"><header><h1>NANGNYAMAI</h1><p>Restaurant Name : NangNyamai</p><p>Company No      : —</p><p>Address         : —</p><p>Tel             : —</p><h2>RECEIPT</h2></header><section><p>Customer Name : {customerName}</p><p>Phone No      : {phone}</p><p>Member No     : {memberId}</p><p className="receipt-gap">Table No      : {order.restaurant_tables?.table_number ?? "—"}</p><p>Receipt No    : —</p><p>Order No      : #{order.order_number}</p><p>Date          : {new Date(order.created_at).toLocaleDateString("en-MY", { timeZone: "Asia/Kuala_Lumpur" })}</p><p>Print On      : {new Date(order.updated_at).toLocaleString("en-MY", { timeZone: "Asia/Kuala_Lumpur" })}</p></section><section className="receipt-items"><p>QTY  ITEM                                  RM</p><p>--------------------------------------------</p><p className="receipt-center">*** Dine In ***</p>{order.order_items.map((item, index) => <p key={`${item.item_name_snapshot}-${index}`}>{String(item.quantity).padStart(3)}  {item.item_name_snapshot.slice(0, 30).padEnd(30)} {money(Number(item.unit_price) * item.quantity).padStart(7)}</p>)}<p>--------------------------------------------</p><p>{"Subtotal".padEnd(35)} {money(Number(order.subtotal)).padStart(7)}</p><p>{"Service Charge".padEnd(35)} {money(Number(order.service_charge)).padStart(7)}</p><p>{"Net Total".padEnd(35)} {money(Number(order.total)).padStart(7)}</p><p>--------------------------------------------</p><p>{(order.payment_method === "cash" ? "Cash" : "Card").padEnd(35)} {money(Number(order.total)).padStart(7)}</p><p>Transaction Ref : —</p><p>AutoCount Ref   : —</p><p className="receipt-gap">e-Invoice</p><p>—</p><p>QR Code</p><p>—</p><p className="receipt-center receipt-gap">THANK YOU, PLEASE COME AGAIN</p><p className="receipt-center">NANGNYAMAI</p></section></article></main>;
}
