"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";

type Receipt = { order_number: string; subtotal: number; service_charge: number; total: number; status: string; payment_status: string; payment_method: string | null; created_at: string; updated_at: string; customer_id: string | null; restaurant_tables: { table_number: string } | null; profiles: { full_name: string | null; phone_number: string | null; member_number: string | null; card_number: string | null; point_before: number | null; point_earned: number | null; point_redeem: number | null; latest_point: number | null } | null; order_items: { item_name_snapshot: string; unit_price: number; quantity: number }[] };
const money = (value: number) => Number(value).toFixed(2);

export function DigitalReceipt({ orderId }: { orderId: string }) {
  const supabase = useMemo(() => createClient(), []); const [order, setOrder] = useState<Receipt | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); const { data, error: queryError } = await supabase.from("orders").select("order_number, subtotal, service_charge, total, status, payment_status, payment_method, created_at, updated_at, customer_id, restaurant_tables!orders_table_id_fkey(table_number), order_items(item_name_snapshot, unit_price, quantity)").eq("id", orderId).maybeSingle(); if (queryError) { setError("Unable to load the receipt right now."); setLoading(false); return; } if (!data) { setError("Receipt is not available for this order."); setLoading(false); return; } let profile: Receipt["profiles"] = null; if (data.customer_id) { const { data: profileData } = await supabase.from("profiles").select("full_name, phone_number, member_number, card_number, point_before, point_earned, point_redeem, latest_point").eq("id", data.customer_id).maybeSingle(); profile = profileData as Receipt["profiles"]; } setOrder({ ...(data as unknown as Receipt), profiles: profile }); setLoading(false); }, [orderId, supabase]);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  if (loading) return <main className="receipt-page"><span>Loading receipt…</span></main>;
  const valid = order && order.status === "completed" && order.payment_status === "paid" && (order.payment_method === "cash" || order.payment_method === "card");
  if (!order || !valid) return <main className="receipt-page"><Link className="details-back receipt-control" href="/staff/payments">← <span>Back to Payment Processing</span></Link><div className="status-error">{error || "Receipt is not available for this order."}</div></main>;
  return <main className="receipt-page"><div className="receipt-controls"><Link className="details-back" href={`/staff/payments/${orderId}/complete`}>← <span>Back to Payment Successful</span></Link><button type="button" onClick={() => window.print()}>Print Receipt</button></div><article className="digital-receipt"><header><h1>NANGNYAMAI</h1><p>Restaurant Name : NangNyamai</p><p>Company No      : —</p><p>Address         : —</p><p>Tel             : —</p><h2>RECEIPT</h2></header><section><p>Customer Name : {order.profiles?.full_name?.trim() || "—"}</p><p>Phone No      : {order.profiles?.phone_number?.trim() || "—"}</p><p>Member No     : {order.profiles?.member_number?.trim() || "—"}</p><p>Card No       : {order.profiles?.card_number?.trim() || "—"}</p><p>Point Before  : {order.profiles?.point_before ?? "—"}</p><p>Point Earned  : {order.profiles?.point_earned ?? "—"}</p><p>Point Redeem  : {order.profiles?.point_redeem ?? "—"}</p><p>Latest Point  : {order.profiles?.latest_point ?? "—"}</p><p className="receipt-gap">Table No      : {order.restaurant_tables?.table_number ?? "—"}</p><p>Receipt No    : —</p><p>Order No      : #{order.order_number}</p><p>Date          : {new Date(order.created_at).toLocaleDateString("en-MY", { timeZone: "Asia/Kuala_Lumpur" })}</p><p>Completed On   : {new Date(order.updated_at).toLocaleString("en-MY", { timeZone: "Asia/Kuala_Lumpur" })}</p><p>Print On       : {new Date().toLocaleString("en-MY", { timeZone: "Asia/Kuala_Lumpur" })}</p></section><section className="receipt-items"><p>QTY  ITEM                                  RM</p><p>--------------------------------------------</p><p className="receipt-center">*** Dine In ***</p>{order.order_items.map((item, index) => <p key={`${item.item_name_snapshot}-${index}`}>{String(item.quantity).padStart(3)}  {item.item_name_snapshot.slice(0, 30).padEnd(30)} {money(Number(item.unit_price) * item.quantity).padStart(7)}</p>)}<p>--------------------------------------------</p><p>{"Subtotal".padEnd(35)} {money(Number(order.subtotal)).padStart(7)}</p><p>{"Service Charge".padEnd(35)} {money(Number(order.service_charge)).padStart(7)}</p><p>{"Net Total".padEnd(35)} {money(Number(order.total)).padStart(7)}</p><p>--------------------------------------------</p><p>{(order.payment_method === "cash" ? "Cash" : "Card").padEnd(35)} {money(Number(order.total)).padStart(7)}</p><p>Transaction Ref : —</p><p>AutoCount Ref   : —</p><p className="receipt-gap">e-Invoice</p><p>—</p><p>QR Code</p><p>—</p><p className="receipt-center receipt-gap">THANK YOU, PLEASE COME AGAIN</p><p className="receipt-center">NANGNYAMAI</p></section></article></main>;
}



