"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";
import { ORDER_STATUS_LABELS, ORDER_STATUS_TRANSITIONS, PAYMENT_STATUS_LABELS } from "@/constants/status";
import type { OrderStatus } from "@/types/database";

type Detail = { id:string; order_number:string; status:OrderStatus; subtotal:number; service_charge:number; total:number; payment_status:string; special_note:string|null; created_at:string; restaurant_tables:{table_number:string}|null; order_items:{item_name_snapshot:string;unit_price:number;quantity:number;note:string|null;selected_options:Record<string,unknown>|null}[] };
const money = new Intl.NumberFormat("en-MY", { style:"currency", currency:"MYR", currencyDisplay:"narrowSymbol" });

export function OrderDetails({ orderId }: { orderId:string }) {
  const supabase = useMemo(() => createClient(), []); const [order,setOrder] = useState<Detail|null>(null); const [error,setError] = useState<"not-found"|"access"|"network"|"">(""); const [busy,setBusy] = useState(false); const [rejected,setRejected] = useState(false);
  useEffect(() => { void (async()=>{ const {data,error:e}=await supabase.from("orders").select("id, order_number, status, subtotal, service_charge, total, payment_status, special_note, created_at, restaurant_tables!orders_table_id_fkey(table_number), order_items(item_name_snapshot, unit_price, quantity, note, selected_options)").eq("id",orderId).single(); if(e)setError(e.code==="PGRST116"?"not-found":e.code==="42501"?"access":"network"); else setOrder(data as unknown as Detail); })(); },[orderId,supabase]);
  async function updateOne(next:OrderStatus,current:OrderStatus){ return (await supabase.from("orders").update({status:next}).eq("id",orderId).eq("status",current)).error; }
  async function sendToKitchen(){ if(!order)return; setBusy(true); setError(""); if(order.status==="received"){const e=await updateOne("verified","received");if(e){setError(e.code==="42501"?"access":"network");setBusy(false);return;}} const e=await updateOne("preparing","verified"); if(e){if(order.status==="received")await updateOne("received","verified");setError(e.code==="42501"?"access":"network");setBusy(false);return;} window.location.assign(`/staff/orders/${order.id}/sent-to-kitchen`);}
  async function reject(){if(!order||!ORDER_STATUS_TRANSITIONS[order.status].includes("cancelled")||!window.confirm("Are you sure you want to cancel this order?"))return;setBusy(true);const e=await updateOne("cancelled",order.status);if(e){setError(e.code==="42501"?"access":"network");setBusy(false);}else{setOrder({...order,status:"cancelled"});setRejected(true);setBusy(false);}}
  if(error)return <main className="order-details"><Link className="details-back" href="/staff/orders">← <span>Back to Order Queue</span></Link><div className="queue-state"><strong>{error==="not-found"?"Order not found.":error==="access"?"You do not have access to this order.":"Unable to load this order right now."}</strong><span>Please return to the order queue and try again.</span></div></main>;
  if(!order)return <main className="order-details"><span>Loading order…</span></main>;
  const canSend=order.status==="received"||order.status==="verified";
  return <main className="order-details"><Link className="details-back" href="/staff/orders">← <span>Back to Order Queue</span></Link><div className="details-top"><header className="details-header"><div><p>Order details</p><h1>#{order.order_number}</h1><span>Table {order.restaurant_tables?.table_number??"—"} · {new Date(order.created_at).toLocaleString("en-MY")}</span></div><span className={`order-status ${order.status==="completed"?"completed":"new"}`}>{order.status==="received"?"NEW":order.status==="cancelled"?"REJECTED":ORDER_STATUS_LABELS[order.status]}</span></header><div className="details-actions">{ORDER_STATUS_TRANSITIONS[order.status].includes("cancelled")&&<button className="details-danger" type="button" onClick={()=>void reject()} disabled={busy}>Reject Order</button>}{canSend&&<button type="button" onClick={()=>void sendToKitchen()} disabled={busy}>{busy?"Sending…":"Send to Kitchen"}</button>}{rejected&&<div className="details-rejected-message"><strong>Order Rejected</strong><span>This order has been cancelled and will not be sent to the kitchen.</span></div>}</div></div><section className="details-panel"><h2>Order Items</h2>{order.order_items.map((item,i)=><div className="details-item" key={`${item.item_name_snapshot}-${i}`}><div><strong>{item.item_name_snapshot}</strong>{item.note&&<small>Note: {item.note}</small>}{item.selected_options&&<small>Options: {Object.entries(item.selected_options).map(([k,v])=>`${k}: ${String(v)}`).join(", ")}</small>}</div><span>{item.quantity} × {money.format(Number(item.unit_price))}</span></div>)}<div className="details-total"><span>Subtotal</span><strong>{money.format(Number(order.subtotal))}</strong><span>Service charge</span><strong>{money.format(Number(order.service_charge))}</strong><span>Total</span><strong>{money.format(Number(order.total))}</strong><span>Payment</span><strong>{PAYMENT_STATUS_LABELS[order.payment_status as keyof typeof PAYMENT_STATUS_LABELS]??order.payment_status}</strong></div></section>{order.special_note&&<section className="details-panel"><h2>Order Note</h2><p>{order.special_note}</p></section>}</main>;
}
