"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";

type PaymentOrder = { id: string; order_number: string; status: string; payment_status: string; payment_method: string | null; subtotal: number; service_charge: number; total: number; restaurant_tables: { table_number: string } | null; order_items: { item_name_snapshot: string; unit_price: number; quantity: number }[] };
const money = new Intl.NumberFormat("en-MY", { style: "currency", currency: "MYR", currencyDisplay: "narrowSymbol", minimumFractionDigits: 2 });

export function PaymentDetails({ orderId }: { orderId: string }) {
  const supabase = useMemo(() => createClient(), []); const [order, setOrder] = useState<PaymentOrder | null>(null); const [method, setMethod] = useState<"cash" | "card" | "">(""); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); const { data, error: queryError } = await supabase.from("orders").select("id, order_number, status, payment_status, payment_method, subtotal, service_charge, total, restaurant_tables!orders_table_id_fkey(table_number), order_items(item_name_snapshot, unit_price, quantity)").eq("id", orderId).maybeSingle(); if (queryError) setError("Unable to load this order right now."); else if (!data) setError("Order not found."); else setOrder(data as unknown as PaymentOrder); setLoading(false); }, [orderId, supabase]);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  async function confirmPayment() { if (!method || !order || order.status !== "ready" || order.payment_status !== "unpaid") return; setBusy(true); setError(""); setMessage(""); try { const response = await fetch(`/api/staff/orders/${order.id}/payment`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ paymentMethod: method }) }); const result = await response.json().catch(() => null); if (!response.ok) { setError(result?.error ?? "Unable to process payment right now."); return; } window.location.assign(`/staff/payments/${order.id}/complete`); } catch { setError("Unable to process payment right now."); } finally { setBusy(false); } }
  if (loading) return <main className="status-page"><span>Loading payment order…</span></main>;
  if (!order) return <main className="status-page"><Link className="details-back" href="/staff/payments">← <span>Back to Payment Processing</span></Link><div className="status-error">{error || "Order not found."}</div></main>;
  const eligible = order.status === "ready" && order.payment_status === "unpaid";
  return <main className="status-page"><Link className="details-back" href="/staff/payments">← <span>Back to Payment Processing</span></Link><header className="status-page-header"><p>Staff payment</p><h1>Payment Processing</h1></header><section className="status-summary"><div><small>Order ID</small><strong>#{order.order_number}</strong></div><div><small>Table</small><strong>{order.restaurant_tables?.table_number ?? "—"}</strong></div><div><small>Total Amount</small><strong>{money.format(Number(order.total))}</strong></div></section><section className="details-panel"><h2>Order Summary</h2>{order.order_items.map((item, index) => <div className="details-item" key={`${item.item_name_snapshot}-${index}`}><div><strong>{item.item_name_snapshot}</strong></div><span>{item.quantity} × {money.format(Number(item.unit_price))}</span></div>)}<div className="details-total"><span>Subtotal</span><strong>{money.format(Number(order.subtotal))}</strong><span>Service Charge</span><strong>{money.format(Number(order.service_charge))}</strong><span>Total</span><strong>{money.format(Number(order.total))}</strong></div></section>{!eligible && <div className="status-error">This order is not eligible for payment. It must be ready and unpaid.</div>}{message && <div className="status-notice">{message}</div>}{error && <div className="status-error">{error}</div>}{eligible && <section className="details-panel"><h2>Payment Method</h2><div className="status-choices"><button type="button" className={method === "cash" ? "selected" : ""} onClick={() => setMethod("cash")} disabled={busy}>Cash</button><button type="button" className={method === "card" ? "selected" : ""} onClick={() => setMethod("card")} disabled={busy}>Card</button></div><button className="status-submit" type="button" disabled={!method || busy} onClick={() => void confirmPayment()}>{busy ? "Processing…" : "Confirm Payment"}</button></section>}</main>;
}
