"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useCallback, useEffect, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";
import { ORDER_STATUS_LABELS, ORDER_STATUS_TRANSITIONS } from "@/constants/status";
import type { OrderStatus } from "@/types/database";

type StatusOrder = { id: string; order_number: string; status: OrderStatus; total: number; restaurant_tables: { table_number: string } | null };
const choices: OrderStatus[] = ["preparing", "ready", "completed", "cancelled"];
const steps: { status: OrderStatus; label: string }[] = [{ status: "received", label: "New" }, { status: "preparing", label: "Preparing" }, { status: "ready", label: "Ready" }, { status: "completed", label: "Completed" }];

export function UpdateOrderStatus({ orderId }: { orderId: string }) {
  const supabase = useMemo(() => createClient(), []); const router = useRouter();
  const [order, setOrder] = useState<StatusOrder | null>(null); const [selected, setSelected] = useState<OrderStatus | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [stale, setStale] = useState(false);
  const load = useCallback(async () => { const { data, error: fetchError } = await supabase.from("orders").select("id, order_number, status, total, restaurant_tables!orders_table_id_fkey(table_number)").eq("id", orderId).single(); if (fetchError) { setError(fetchError.code === "PGRST116" ? "Order not found." : fetchError.code === "42501" ? "You do not have access to this order." : "Unable to load this order right now."); return; } const next = data as unknown as StatusOrder; setOrder(next); setSelected(next.status); setStale(false); }, [orderId, supabase]);
  useEffect(() => { const initialLoad = window.setTimeout(() => void load(), 0); const channel = supabase.channel(`staff-order-status-${orderId}`).on("postgres_changes", { event: "UPDATE", schema: "public", table: "orders", filter: `id=eq.${orderId}` }, () => void load()).subscribe(); return () => { window.clearTimeout(initialLoad); void supabase.removeChannel(channel); }; }, [load, orderId, supabase]);
  async function updateStatus() { if (!order || !selected || selected === order.status || !ORDER_STATUS_TRANSITIONS[order.status].includes(selected)) return; if (selected === "completed" && !window.confirm("Mark this order as completed?")) return; if (selected === "cancelled" && !window.confirm("Cancel this order?")) return; setBusy(true); setError(""); const { data, error: updateError } = await supabase.from("orders").update({ status: selected }).eq("id", order.id).eq("status", order.status).select("id").maybeSingle(); if (updateError) setError(updateError.code === "42501" ? "You do not have permission to update this order." : "Unable to update this order right now."); else if (!data) { setStale(true); await load(); } else { setOrder({ ...order, status: selected }); setSelected(selected); router.push("/staff/orders"); } setBusy(false); }
  if (error && !order) return <main className="order-details"><Link className="details-back" href="/staff/orders">← <span>Back to Order Queue</span></Link><div className="queue-state"><strong>{error}</strong><span>Return to the queue and try again.</span></div></main>;
  if (!order) return <main className="order-details"><span>Loading order…</span></main>;
  const workflowState = order.status === "received" || order.status === "verified";
  const canUpdate = selected !== null && selected !== order.status && !workflowState && ORDER_STATUS_TRANSITIONS[order.status].includes(selected);
  const progressIndex = order.status === "received" || order.status === "verified" ? 0 : steps.findIndex((step) => step.status === order.status);
  return <main className="status-page"><Link className="details-back" href="/staff/orders">← <span>Back to Order Queue</span></Link><header className="status-page-header"><div><p>Staff workflow</p><h1>Update Order Status</h1></div></header><section className="status-summary"><div><small>Order ID</small><strong>#{order.order_number}</strong></div><div><small>Table</small><strong>{order.restaurant_tables?.table_number ?? "—"}</strong></div><div><small>Total Amount</small><strong>RM {Number(order.total).toFixed(2)}</strong></div></section>{workflowState ? <section className="status-notice"><strong>This order has not been sent to the kitchen.</strong><span>Review it first, then use Send to Kitchen from Order Details.</span><Link href={`/staff/orders/${order.id}`}>Open Order Details</Link></section> : <><section className="progress-panel"><h2>Order Progress</h2><div className="status-progress">{steps.map((step, index) => <div className={`progress-step ${index < progressIndex ? "done" : index === progressIndex ? "current" : "upcoming"}`} key={step.status}><span>{index < progressIndex ? "✓" : index + 1}</span><small>{step.label}</small></div>)}</div></section><section className="status-choices" aria-label="Choose order status">{choices.map((choice) => { const valid = choice === order.status || ORDER_STATUS_TRANSITIONS[order.status].includes(choice); return <button key={choice} type="button" className={selected === choice ? "selected" : ""} disabled={!valid || busy || order.status === "completed" || order.status === "cancelled"} onClick={() => setSelected(choice)}>{choice === "cancelled" ? "Cancel Order" : ORDER_STATUS_LABELS[choice]}</button>; })}</section>{stale && <div className="status-error">This order was updated by another staff member. The latest status has been loaded.</div>} {error && <div className="status-error">{error}</div>}<button className="status-submit" type="button" onClick={() => void updateStatus()} disabled={!canUpdate || busy}>{busy ? "Updating…" : "Update Status"}</button></>}</main>;
}
