import { createClient } from "@/lib/supabase/server";
import { ORDER_STATUS_LABELS } from "@/constants/status";
import Link from "next/link";

const statuses = ["received", "verified", "preparing", "ready", "completed"] as const;

export default async function OrderTrackingPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const supabase = await createClient();
  const { data: order } = await supabase.from("orders").select("id, order_number, status, payment_status, subtotal, service_charge, total, created_at, table_id").eq("id", id).maybeSingle();
  const { data: orderItems } = order ? await supabase.from("order_items").select("item_name_snapshot, quantity, unit_price").eq("order_id", order.id) : { data: null };

  if (!order) return <main className="heritage-pattern mx-auto min-h-screen max-w-lg p-6"><div className="rounded-[var(--radius-xl)] bg-white p-7 text-center shadow-[var(--shadow-soft)]"><h1 className="text-2xl font-bold text-[var(--charcoal)]">Order tidak ditemui</h1><p className="mt-2 text-sm text-[var(--secondary-text)]">Order ini mungkin tidak boleh diakses atau belum tersedia.</p><Link href="/order" className="mt-6 inline-flex min-h-11 items-center rounded-full bg-[var(--sarawak-red)] px-5 text-sm font-bold text-white">Kembali ke menu</Link></div></main>;

  const currentIndex = statuses.indexOf(order.status as (typeof statuses)[number]);
  return <main className="heritage-pattern mx-auto min-h-screen max-w-lg px-5 py-8"><header><p className="text-xs font-bold uppercase tracking-[0.2em] text-[var(--sarawak-red)]">NangNyamai</p><h1 className="mt-2 text-3xl font-bold text-[var(--charcoal)]">Track order</h1><p className="mt-1 text-sm text-[var(--secondary-text)]">#{order.order_number}</p></header><section className="mt-8 rounded-[var(--radius-xl)] bg-white p-6 shadow-sm"><h2 className="text-lg font-bold text-[var(--charcoal)]">Order status</h2><ol className="mt-6 space-y-5">{statuses.map((status, index) => { const active = status === order.status; const complete = currentIndex >= index; return <li key={status} className="flex items-start gap-3"><span className={`mt-0.5 flex h-8 w-8 shrink-0 items-center justify-center rounded-full text-sm font-bold ${complete ? "bg-[var(--sarawak-red)] text-white" : "bg-[var(--soft-sand)]/50 text-[var(--secondary-text)]"}`} aria-hidden="true">{complete ? "✓" : index + 1}</span><div><p className={`font-semibold ${active ? "text-[var(--sarawak-red)]" : "text-[var(--charcoal)]"}`}>{ORDER_STATUS_LABELS[status]}</p><p className="text-xs text-[var(--secondary-text)]">{active ? "Status semasa order anda." : complete ? "Status selesai." : "Menunggu langkah ini."}</p></div></li>; })}</ol></section><section className="mt-4 rounded-[var(--radius-lg)] bg-white p-6 shadow-sm"><h2 className="text-lg font-bold text-[var(--charcoal)]">Order details</h2><div className="mt-4 space-y-2 text-sm">{orderItems?.map((item) => <div key={`${item.item_name_snapshot}-${item.quantity}`} className="flex justify-between gap-4"><span>{item.quantity} × {item.item_name_snapshot}</span><span className="font-semibold">RM {(Number(item.unit_price) * item.quantity).toFixed(2)}</span></div>)}<div className="mt-3 flex justify-between border-t border-[var(--soft-sand)] pt-3 font-bold"><span>Total</span><span className="text-[var(--sarawak-red)]">RM {Number(order.total).toFixed(2)}</span></div></div><p className="mt-4 text-xs text-[var(--secondary-text)]">Payment: <span className="capitalize">{order.payment_status}</span></p></section></main>;
}
