import { createClient } from "@/lib/supabase/server";
import { ORDER_STATUS_LABELS } from "@/constants/status";
import Link from "next/link";
import { BackToMenu } from "@/components/customer/back-to-menu";

const statuses = ["received", "verified", "preparing", "ready", "completed"] as const;

export default async function OrderTrackingPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const supabase = await createClient();
  const { data: order } = await supabase.from("orders").select("id, order_number, status, payment_status, total, restaurant_tables(table_number)").eq("id", id).maybeSingle();
  const { data: orderItems } = order ? await supabase.from("order_items").select("item_name_snapshot, quantity, unit_price").eq("order_id", order.id) : { data: null };
  if (!order) return <main className="heritage-pattern mx-auto min-h-screen max-w-lg p-6"><div className="rounded-[var(--radius-xl)] bg-[var(--surface)] p-7 text-center"><h1 className="text-2xl font-bold text-[var(--text-primary)]">Order tidak ditemui</h1><Link href="/order" className="mt-6 inline-flex min-h-11 items-center rounded-full bg-[var(--primary-green)] px-5 text-sm font-bold text-white">Kembali ke menu</Link></div></main>;
  const currentIndex = statuses.indexOf(order.status as (typeof statuses)[number]);
  const tableNumber = Array.isArray(order.restaurant_tables) ? order.restaurant_tables[0]?.table_number : order.restaurant_tables?.table_number;
  const mainMenuHref = tableNumber ? `/order?table=${encodeURIComponent(tableNumber)}` : "/order";
  const eligible = order.status === "completed" && order.payment_status === "paid";
  return <main className="heritage-pattern mx-auto min-h-screen max-w-lg px-5 py-8"><header><p className="text-xs font-bold uppercase tracking-[0.2em] text-[var(--primary-green)]">NangNyamai</p><h1 className="mt-2 text-3xl font-bold text-[var(--text-primary)]">Track order</h1><p className="mt-1 text-sm text-[var(--text-secondary)]">#{order.order_number}</p></header><section className="mt-8 rounded-[var(--radius-xl)] bg-[var(--surface)] p-6"><h2 className="text-lg font-bold text-[var(--text-primary)]">Order status</h2><ol className="mt-6 space-y-5">{statuses.map((status, index) => { const complete = currentIndex >= index; return <li key={status} className="flex items-start gap-3"><span className={`flex h-8 w-8 shrink-0 items-center justify-center rounded-full font-bold ${complete ? "bg-[var(--primary-green)] text-white" : "bg-[var(--surface-muted)] text-[var(--text-secondary)]"}`}>{complete ? "✓" : index + 1}</span><div><p className={`font-semibold ${status === order.status ? "text-[var(--gold-accent)]" : "text-[var(--text-primary)]"}`}>{ORDER_STATUS_LABELS[status]}</p><p className="text-xs text-[var(--text-secondary)]">{status === order.status ? "Status semasa order anda." : complete ? "Status selesai." : "Menunggu langkah ini."}</p></div></li>; })}</ol></section><section className="mt-4 rounded-[var(--radius-lg)] bg-[var(--surface)] p-6"><h2 className="text-lg font-bold text-[var(--text-primary)]">Order details</h2><div className="mt-4 space-y-2 text-sm text-[var(--text-primary)]">{orderItems?.map((item) => <div key={`${item.item_name_snapshot}-${item.quantity}`} className="flex justify-between gap-4"><span>{item.quantity} × {item.item_name_snapshot}</span><span>RM {(Number(item.unit_price) * item.quantity).toFixed(2)}</span></div>)}<div className="mt-3 flex justify-between border-t border-[var(--border-soft)] pt-3 font-bold"><span>Total</span><span className="text-[var(--gold-accent)]">RM {Number(order.total).toFixed(2)}</span></div></div><p className="mt-4 text-xs text-[var(--text-secondary)]">Payment: {order.payment_status}</p>{eligible && <Link href={`/order/${order.id}/feedback`} className="mt-5 inline-flex min-h-11 w-full items-center justify-center rounded-full bg-[var(--primary-green)] px-5 text-sm font-bold text-white">Give feedback / Beri maklum balas</Link>}<BackToMenu href={mainMenuHref} className="mt-4 w-full" /></section></main>;
}
